### PR TITLE
Fix Broken specs on Travis

### LINKED ISSUE #179: Fix broken specs on Travis
Today we have broken specs on [Travis](https://travis-ci.org/michaeldv/awesome_print/builds/46768105).

The specs *Works On My Machine™*.

Need to debug why this occurs.

### PR DESCRIPTION
**Pull request by maurogeorge**
Closes #179 

:warning: :warning: Work In Progress, do not merge yet

Trying to fix travis errors.

### CODE REVIEW

**Comment by maurogeorge** [comment]
I lost my internet conection yesterday, so I cannot bundle on 1.9.3 to try fix this.
When I have some time I will try to fix this, but if anyone has a solution a PR is welcome :D

**Comment by maurogeorge** [comment]
Close, since I cant reproduce the error on my local enviroment

**Comment by maurogeorge** [comment]
@guiloyins I found the issue, take a look [this commit](https://github.com/maurogeorge/awesome_print/commit/3f7137ce0035d6b433b3e2f6b11f6439d4cac6b0). Thanks for your help :star:

**Comment by guiloyins** [comment]
Great @maurogeorge. :star:

**Pull request merged**
