### PR TITLE
Move from begin/rescue/end (BRE) to RSpec metadata when running adapters specs

### PR DESCRIPTION
**Pull request by maurogeorge**

### CODE REVIEW

**Comment by imajes** [comment]
OK, this looks good but you've mixed in whitespace/formatting changes with actual functional changes. Do you think we can run a separate branch first which does the whitespace change, so that we can get clean commits?

thanks!

**Comment by maurogeorge** [comment]
@imajes I guess I do not touch formatting, the whitespace I create a [PR to remove some](https://github.com/michaeldv/awesome_print/pull/176) maybe I miss some.

I guess it is hard to see the changes because I usualy remove a full ident of code, because I removed the BRE. I think the better way to you review is clicking the "view" button on each file under the "Files Changed" tab on top.

**Comment by imajes** [comment]
Yeah, i guess the BRE really did screw with the indentation. It's frustrating because that change kinda gets lost in the noise of the re-indent. I think we'll just have to accept it. i'll merge this in a bit.

**Comment by imajes** [comment]
Done. merged via rebase. good work!

**Pull request closed without merging**
