### PR TITLE
Fix NoBrainer tests

### PR DESCRIPTION
**Pull request by nviennot**

### CODE REVIEW

**Comment by gerrywastaken** [comment]
Thank you. :)

**Comment by gerrywastaken** [comment]
Oh despite those tests now passing on Travis, when I run `rspec` on local I get the following:

```
  3) AwesomePrint/NoBrainer should print class instance
     Failure/Error: NoBrainer.configure { |c| c.app_name = "ap_test" }

     URI::InvalidURIError:
       bad URI(is not URI?): rethinkdb://localhost/ap_test_{}
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/connection.rb:14:in `parse_uri'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/connection.rb:9:in `initialize'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `new'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `block in validate_urls'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `map'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `validate_urls'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:60:in `assert_valid_options'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:77:in `configure'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/nobrainer.rb:25:in `configure'
     # ./spec/ext/nobrainer_spec.rb:7:in `block (2 levels) in <top (required)>'

  4) AwesomePrint/NoBrainer should print the class
     Failure/Error: NoBrainer.configure { |c| c.app_name = "ap_test" }

     URI::InvalidURIError:
       bad URI(is not URI?): rethinkdb://localhost/ap_test_{}
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/connection.rb:14:in `parse_uri'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/connection.rb:9:in `initialize'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `new'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `block in validate_urls'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `map'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:130:in `validate_urls'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:60:in `assert_valid_options'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/no_brainer/config.rb:77:in `configure'
     # /Users/gerry/.gem/ruby/2.3.1/gems/nobrainer-0.31.0/lib/nobrainer.rb:25:in `configure'
     # ./spec/ext/nobrainer_spec.rb:7:in `block (2 levels) in <top (required)>'
```

Any clue about this? I'm still new to this project so it could be something related to not running the command via `rake`. But it's my suspicion that I should be able to run rspec directly and have these pass. Am I wrong about this?

**Comment by nviennot** [comment]
Set the environment in addition to the app name, like: https://github.com/nviennot/kaminari-nobrainer/blob/master/spec/spec_helper.rb#L8-L11
This should work

**Comment by gerrywastaken** [comment]
@nviennot Thanks for that, it worked.

**Comment by nviennot** [comment]
awesome

**Comment by gerrywastaken** [comment]
For posterity: this went live in version 1.7.0. Thank you for your work.

**Comment by nviennot** [comment]
👍

**Pull request merged**
