### PR TITLE
Update NoBrainer awesome prints

### PR DESCRIPTION
**Pull request by nviennot**

### CODE REVIEW

**Comment by nviennot** [comment]
> Hi @nviennot, could you please create the specs for nobrainer?

All there :)

**Comment by maurogeorge** [comment]
@nviennot thanks for the PR :star2:

**Comment by gerrywastaken** [comment]
@nvienot It seems these specs break on Travis CI. It appears the last time there was a successful build on master these tests were skipped due to the `has_nobrainer?` check, however it seems that is no longer the case.

As I have not worked with NoBrainer myself and you are the maintainer I though I would ask. Any chance of a new pull request to fix these tests?

 https://travis-ci.org/michaeldv/awesome_print/jobs/127768687

**Comment by nviennot** [comment]
@gerrywastaken here you go: https://github.com/michaeldv/awesome_print/pull/228

**Comment by gerrywastaken** [comment]
@nviennot Ahh the error mentioned the need to specify an environment so I thought it might have been more than that. Thanks heaps for the fix. :)

**Pull request merged**
